### ISSUE TITLE
Can not upload same file twice on web floppa files

### ISSUE THREAD

**Issue by callmewoem** [gosher-studios/floppa-files#9]
Action: 
press upload file, then do it again with the same file

Expected result: 
2 files uploaded

Real result:
1 file uploaded, second doesn't show up

Is it even worth fixing as you probably shouldn't upload the same file multiple times, but it is filename-dependent, not file content so shoud probably be fixed
@chxry

**Comment by callmewoem** [comment]
revised issue, only happens on chromium

**Comment by chxry** [comment]
fixed in #8
